CREATE TABLE USERS (
  NAME VARCHAR(200) NOT NULL,
  ENCRYPTED_PASSWORD VARCHAR(200) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE EMPLOYEE (
  ID NUMBER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(200) NOT NULL,
  SUPERVISOR_ID NUMBER,
  PRIMARY KEY (ID)
);
 
 CREATE UNIQUE INDEX "EMPLOYEE_NAME" ON "EMPLOYEE"
  (
    "NAME"
  );

