CREATE TABLE USERS (
  NAME VARCHAR(200) NOT NULL,
  ENCRYPTED_PASSWORD VARCHAR(200) NOT NULL,
  PRIMARY KEY (NAME)
);

CREATE TABLE EMPLOYEE (
  ID NUMBER,
  NAME VARCHAR(200) NOT NULL,
  SUPERVISOR_ID NUMBER,
  PRIMARY KEY (ID)
);
  
CREATE SEQUENCE EMPLOYEE_ID_SEQ
  MINVALUE 1
  MAXVALUE 9999999999999
  START WITH 1
  INCREMENT BY 1;
 
 CREATE UNIQUE INDEX "EMPLOYEE_NAME" ON "EMPLOYEE"
  (
    "NAME"
  );

