version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysql_db
    command: sh -c './wait-for mysql_db:3306 --timeout=0 --strict -- java -jar /employees-hierarchy.jar'
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: personia
      MYSQL_ROOT_PASSWORD: sysadmin@123